version: 1.0.{build}.{branch}
configuration: AppVeyor
install:
  - set PATH=C:\Ruby21\bin;%PATH%
  - gem install ocra
build:
  project: tool\NinjaScanLight_tools.sln
  verbosity: minimal
after_build:
  - type nul > %APPVEYOR_REPO_COMMIT%.commit
  - 7z a windows.%APPVEYOR_REPO_BRANCH%.zip %APPVEYOR_BUILD_FOLDER%\tool\build_VC\%CONFIGURATION%\*.exe %APPVEYOR_REPO_COMMIT%.commit
artifacts:
  - path: windows.*.zip
    name: x86 binary
before_deploy:
  - echo on
    & for /f "usebackq delims=" %%a in (`git log --pretty^=format:%%cd -n 1`) do set TIMESTAMP="%%a"
    & for /f "usebackq delims=" %%a in (`ruby -e 'require "time"^; print Time::parse^(ENV["TIMESTAMP"]^).strftime^("%%Y%%m%%d_%%H%%M%%S"^)'`) do set TIMESTAMP=%%a
deploy:
  - provider: BinTray
    username: fenrir-naru
    api_key:
      secure: 9aElrrL3YTy/8XlhblScghgwtorv/6LRNnBkvz5v3OWPoAss903yzMQ9VfsjHzMk
    subject: fenrir-naru
    repo: github
    package: ninja-scan-light
    version: $(TIMESTAMP)/$(TIMESTAMP)
    publish: true
    override: true
    explode: false
    on:
      branch: master